//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Comments1 = new HashSet<Comment>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ReceiptDetails = new HashSet<ReceiptDetail>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }

        [Range(0,999999999999)]
        [Required(ErrorMessage = "Please enter a non-negative price")]
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string Configuration { get; set; }
        public string Description { get; set; }
        public string Img { get; set; }
        [Range(0, 999999999999)]
        [Required(ErrorMessage = "Please enter a non-negative Quantity")]
        public Nullable<int> Quantity { get; set; }
        [Range(0, 999999999999)]
        [Required(ErrorMessage = "Please enter a non-negative Views")]
        public Nullable<int> Views { get; set; }
        public Nullable<int> votes { get; set; }
        public Nullable<int> Comments { get; set; }
        public Nullable<int> Purchases { get; set; }
        public Nullable<int> New { get; set; }
        public Nullable<int> ManufactureID { get; set; }
        public Nullable<int> ProducerID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }
        public string Img4 { get; set; }

        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments1 { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Producer Producer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDetail> ReceiptDetails { get; set; }
    }
}
